[package]
name = "falling_sand"
version = "0.1.0"
authors = ["anmej"]

[dependencies]
rand = "0.3"

# pistoncore-sdl2_window = "0.4.0"
# piston = "0.3"
# piston2d-opengl_graphics = "0.21"
# piston2d-graphics = "0.4"
image = "0.5.4"
piston_window = "0.32"
